name: Commit comments
on:
  push:
    branches:
      - main

jobs:
  comments:
    name: Commit comments
    runs-on: ubuntu-latest
    steps:
      - name: Debug Message
        run: echo "Workflow is running"
      - name: Comment on commit
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
